dataset:
  root: data/raw_detection
  yaml_path: data/raw_detection/data.yaml
  task: detect
  class_names:
    - 2wheelers
    - auto
    - bus
    - car
    - pedestrian
    - truck
  num_classes: 6

preprocess:
  copy_to_processed: true
  processed_root: data/processed_detection
  check_images: true
  check_labels: true