target_platform: rk3588

quantization:
  do_quantization: false
  dataset: data/processed_detection/images/val
  dataset_size: 100
  quantized_dtype: asymmetric_quantized-8
  pre_compile: false

io_config:
  input_size_list:
    - [1, 3, 640, 640]
  mean_values:
    - [0, 0, 0]
  std_values:
    - [255, 255, 255]

npu_core_mask: RKNN_NPU_CORE_AUTO

perf_debug: false
eval_mem: false

output:
  onnx_model: models/export_detection/model.onnx
  rknn_model: models/export_detection/model.rknn
  perf_report: models/export_detection/rknn_perf_report.json