# 分类 RKNN 模型转换配置
target_platform: rk3588

# 修改成你自己的 rknn311 Python 路径
python_exec: /home/pc/anaconda3/envs/rknn311/bin/python

quantization:
  do_quantization: true
  dataset: data/processed/val/
  dataset_size: 100
  quantized_dtype: asymmetric_quantized-8
  pre_compile: false

io_config:
  input_size_list: [[1, 3, 224, 224]]
  mean_values: [[123.675, 116.28, 103.53]]
  std_values: [[58.395, 57.12, 57.375]]

npu_core_mask: RKNN_NPU_CORE_AUTO

perf_debug: false
eval_mem: false
check_output_shapes: true

output:
  onnx_model: models/export/model.onnx
  rknn_model: models/export/model.rknn
  perf_report: models/export/rknn_perf_report.json